<a href="https://colab.research.google.com/github/cybersid123/AI-ML/blob/main/Data_Analysis_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

1> Vectors - 1D Array 2> Matrices - 2D Arrays

In [ ]:
import numpy as np

my_list = [1,2,3]
**bold text**


In [ ]:
my_matrix

np.array(my_matrix)

my_matrix

np.arange(5,100,5)

np.linspace(0,11)

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
my_list = [1,2,3]

my_list

np.array(my_list)

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

np.random.randint(1)




0

#Random


In [ ]:
np.random.rand(3)

np.random.rand(5,5)

array([[0.1018743 , 0.33413173, 0.45734045, 0.81496701, 0.69704751],
       [0.01631816, 0.70056237, 0.97103305, 0.11036206, 0.2319476 ],
       [0.59953145, 0.84839137, 0.76157997, 0.14437657, 0.41372251],
       [0.24923229, 0.25396003, 0.84951192, 0.22152857, 0.91945128],
       [0.8558391 , 0.64861051, 0.91887444, 0.36304082, 0.16730876]])

#Array Attributes and Methods

In [ ]:
arr = np.arange(25)

arr

arr.dtype

dtype('int64')

#NumPy Indexing and Selection

In [ ]:
arr = np.arange(0,11)

arr

arr[1:5]

array([1, 2, 3, 4])

#Broadcasting

In [ ]:
arr[0:5]

slice_array = arr[0:6]

slice_array

slice_array[:] = 100

slice_array

array([100, 100, 100, 100, 100, 100])

#2D Indexing

In [ ]:
import numpy as np


arr2d = np.zeros((10,10))

arr2d

arr_length = arr2d.shape

arr_length

arr = np.arange(1,11)

arr

bool_arr = arr>4

bool_arr


arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

#NumPy Ops


In [ ]:
arr = np.arange(0,10)

arr

arr+arr

5 + arr

arr*3


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])